version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@2.0.0

workflows:
  setup:
    jobs:
      - determine-workflow:
          base_branch: << pipeline.parameters.base_branch >>
          head_branch: << pipeline.parameters.head_branch >>

parameters:
  base_branch:
    type: string
    default: ""
  head_branch:
    type: string
    default: ""

jobs:
  determine-workflow:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: Determine workflow based on branch
          command: .circleci/scripts/select-workflow.sh "<< parameters.base_branch >>" "<< parameters.head_branch >>"

      - run:
          name: printenv
          command: printenv
      - continuation/continue:
          configuration_path: .circleci/workflows/selected_workflow.yml
