version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@2.0.0

workflows:
  setup:
    jobs:
      - determine-workflow

jobs:
  determine-workflow:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: Determine workflow based on branch
          command: .circleci/scripts/select-workflow.sh << pipeline.event.github.pull_request.base.ref >><< pipeline.event.name >>
      - run:
          name: printenv
          command: printenv
      - continuation/continue:
          configuration_path: .circleci/workflows/selected_workflow.yml
