version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.3.1

env: &env
  environment:
    TOFU_VERSION: 1.8.0

defaults: &defaults
  docker:
    - image: cimg/base:2023.03
  resource_class: small
  <<: *env

install_tofu: &install_tofu
  name: Install OpenTofu
  command: .circleci/scripts/install-tofu.sh

install_gcp: &install_gcp
  gcp-cli/setup:
    version: 404.0.0
    gcloud_service_key: DEV_GCLOUD_SERVICE_KEY
    google_project_id: DEV_GCLOUD_PROJECT_ID

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *install_tofu
      - run:
          command: tofu --version
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  init:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          <<: *install_tofu
      - <<: *install_gcp
      - run:
          command: gcloud --version
      - run: tofu init

  plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          <<: *install_tofu
      - run: tofu plan

  apply:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          <<: *install_tofu
      - run: tofu apply

workflows:
  dev-workflow:
    jobs:
      - setup
      - init:
          requires:
            - setup
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
