version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.3.1

env: &env
  environment:
    TOFU_VERSION: 1.8.0
    ENVIRONMENT_NAME: dev
    TERRAFORM_STATE_GCLOUD_STORAGE_BUCKET: $DEV_GCP_TERRAFORM_STATE_BUCKET
    GCLOUD_PROJECT_ID: $DEV_GCLOUD_PROJECT_ID
    GCLOUD_REGION: $DEV_GCLOUD_REGION
    GCLOUD_ZONE: $DEV_GCLOUD_ZONE
    GCLOUD_SERVICE_KEY: ${DEV_GCLOUD_SERVICE_KEY}

defaults: &defaults
  docker:
    - image: cimg/base:2023.03
  resource_class: small
  <<: *env

install_tofu: &install_tofu
  name: Install OpenTofu
  command: |
    .circleci/scripts/install-tofu.sh
    cp $(which tofu) tofu

configure_gcp: &configure_gcp
  name: Configure GCP
  command: |
    echo "$GCLOUD_SERVICE_KEY" > service-account-key.json
    echo "export GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json" >> new-env-vars

persist: &persist
  persist_to_workspace:
    root: .
    paths:
      - .

attach: &attach
  attach_workspace:
    at: .

restore_cache: &restore_cache
  name: Restore cache
  command: |
    # Restore Tofu from cache
    sudo cp tofu /usr/local/bin/tofu

    # Restore custom env variables from cache
    cat new-env-vars >> $BASH_ENV

tofu_init: &tofu_init
  name: Tofu Init
  command: .circleci/scripts/init.sh

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run: *install_tofu
      - run: *configure_gcp
      - *persist

  init:
    <<: *defaults
    steps:
      - *attach
      - run: *restore_cache
      - run: *tofu_init
      - *persist

  plan:
    <<: *defaults
    steps:
      - *attach
      - run: *restore_cache
      - run: |
          tofu plan \
            -var-file=config/environment/dev.tfvars \
            -var="project_id=$DEV_GCLOUD_PROJECT_ID" \
            -var="region=$DEV_GCLOUD_REGION" \
            -var="zone=$DEV_GCLOUD_ZONE" \
            -out=tofuplan
      - *persist

  apply:
    <<: *defaults
    steps:
      - *attach
      - run: *restore_cache
      - run: tofu apply tofuplan

workflows:
  dev-workflow:
    jobs:
      - setup
      - init:
          requires:
            - setup
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
