version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.3.1

env: &env
  environment:
    TOFU_VERSION: 1.8.0

defaults: &defaults
  docker:
    - image: cimg/base:2023.03
  resource_class: small
  <<: *env

install_tofu: &install_tofu
  name: Install OpenTofu
  command: |
    curl -L "https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_amd64.zip" -o tofu.zip
    unzip -o tofu.zip
    sudo install -m 0755 tofu /usr/local/bin/tofu
    rm -rf tofu
    rm -rf tofu.zip
    tofu --version

install_gcp: &install_gcp
  gcp-cli/setup:
    version: 404.0.0
    gcloud_service_key: DEV_GCLOUD_SERVICE_KEY

configure_gcp: &configure_gcp
  name: Configure gcp-cli
  command: |
    echo $DEV_GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    echo 'export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json' >> $BASH_ENV

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *install_tofu
      - run:
          command: tofu --version
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          <<: *install_tofu
      #- run:
      #    <<: *configure_gcp
      - <<: *install_gcp
      - run:
          command: gcloud --version
      - run: |
          tofu --version
          echo "build"

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          <<: *install_tofu
      - run: |
          tofu --version
          echo "test"

workflows:
  dev-workflow:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
